insert into symptoms (id, symptomname) values (1, 'Packera hyperborealis (Greenm.) Á. Löve & D. Löve');
insert into symptoms (id, symptomname) values (2, 'Penstemon tidestromii Pennell');
insert into symptoms (id, symptomname) values (3, 'Hymenaea verrucosa Gaertn.');
insert into symptoms (id, symptomname) values (4, 'Hydrophyllum virginianum L. var. virginianum');
insert into symptoms (id, symptomname) values (5, 'Prunus caroliniana Aiton');
insert into symptoms (id, symptomname) values (6, 'Chaenactis suffrutescens A. Gray');
insert into symptoms (id, symptomname) values (7, 'Blephilia subnuda R. Simmers & Kral');
insert into symptoms (id, symptomname) values (8, 'Parmelinopsis horrescens (Taylor) Elix & Hale');
insert into symptoms (id, symptomname) values (9, 'Andropogon virginicus L.');
insert into symptoms (id, symptomname) values (10, 'Vaccinium simulatum Small');
insert into symptoms (id, symptomname) values (11, 'Euphorbia palmeri Engelm. ex S. Watson');
insert into symptoms (id, symptomname) values (12, 'Umbilicaria Hoffm.');
insert into symptoms (id, symptomname) values (13, 'Hypericum pseudomaculatum Bush');
insert into symptoms (id, symptomname) values (14, 'Mimulus brandegeei Pennell');
insert into symptoms (id, symptomname) values (15, 'Claytonia tuberosa Pall. ex Schult. var. czukczorum (Volkova) Hultén');
insert into symptoms (id, symptomname) values (16, 'Platanthera dilatata (Pursh) Lindl. ex Beck var. albiflora (Cham.) Ledeb.');
insert into symptoms (id, symptomname) values (17, 'Dodecatheon hendersonii A. Gray ssp. parvifolium (R. Knuth) H.J. Thomp.');
insert into symptoms (id, symptomname) values (18, 'Macroptilium lathyroides (L.) Urb. var. lathyroides');
insert into symptoms (id, symptomname) values (19, 'Drymaria effusa A. Gray');
insert into symptoms (id, symptomname) values (20, 'Cryptantha clevelandii Greene var. florosa I.M. Johnst.');
insert into symptoms (id, symptomname) values (21, 'Holocarpha heermannii (Greene) D.D. Keck');
insert into symptoms (id, symptomname) values (22, 'Viola ×slavinii House');
insert into symptoms (id, symptomname) values (23, 'Heterotheca shevockii (Semple) Semple');
insert into symptoms (id, symptomname) values (24, 'Trisetum interruptum Buckley');
insert into symptoms (id, symptomname) values (25, 'Aquilegia eximia Van Houtte ex Planch.');
insert into symptoms (id, symptomname) values (26, 'Hypogymnia vittata (Ach.) Parrique');
insert into symptoms (id, symptomname) values (27, 'Adoxa L.');
insert into symptoms (id, symptomname) values (28, 'Saxifraga texana Buckley');
insert into symptoms (id, symptomname) values (29, 'Mentzelia speciosa Osterh.');
insert into symptoms (id, symptomname) values (30, 'Strongylodon ruber Vogel');
insert into symptoms (id, symptomname) values (31, 'Lomatium hooveri (Mathias & Constance) Constance & Ertter');
insert into symptoms (id, symptomname) values (32, 'Ixora L.');
insert into symptoms (id, symptomname) values (33, 'Sanguinaria canadensis L.');
insert into symptoms (id, symptomname) values (34, 'Arthothelium ruanun (A. Massal.) Körb.');
insert into symptoms (id, symptomname) values (35, 'Terminalia sericea Burch. ex DC.');
insert into symptoms (id, symptomname) values (36, 'Ipomoea pes-caprae (L.) R. Br. ssp. brasiliensis (L.) van Ooststr.');
insert into symptoms (id, symptomname) values (37, 'Eragrostis polytricha Nees');
insert into symptoms (id, symptomname) values (38, 'Sagittaria lancifolia L. ssp. media (Micheli) Bogin');
insert into symptoms (id, symptomname) values (39, 'Pyrostegia C. Presl');
insert into symptoms (id, symptomname) values (40, 'Capparis sandwichiana DC.');
insert into symptoms (id, symptomname) values (41, 'Schaefferia Jacq.');
insert into symptoms (id, symptomname) values (42, 'Hamatocaulis vernicosus (Mitt.) Hedenäs');
insert into symptoms (id, symptomname) values (43, 'Melicope pseudoanisata (Rock) T.G. Hartley & B.C. Stone');
insert into symptoms (id, symptomname) values (44, 'Centaurium Hill');
insert into symptoms (id, symptomname) values (45, 'Phyllocladus Rich. ex Mirb.');
insert into symptoms (id, symptomname) values (46, 'Tradescantia wrightii Rose & Bush');
insert into symptoms (id, symptomname) values (47, 'Teliostachya alopecuroidea (Vahl) Nees');
insert into symptoms (id, symptomname) values (48, 'Adenophorus pinnatifidus Gaudich.');
insert into symptoms (id, symptomname) values (49, 'Carex formosa Dewey');
insert into symptoms (id, symptomname) values (50, 'Asplenium montanum Willd.');
insert into symptoms (id, symptomname) values (51, 'Streptanthus drepanoides Kruckeb. & Morrison');
insert into symptoms (id, symptomname) values (52, 'Eucalyptus loxophleba Benth.');
insert into symptoms (id, symptomname) values (53, 'Viola palustris L.');
insert into symptoms (id, symptomname) values (54, 'Cymopterus williamsii R.L. Hartm. & Constance');
insert into symptoms (id, symptomname) values (55, 'Melanelia multispora (A. Schneid.) Essl.');
insert into symptoms (id, symptomname) values (56, 'Letharia vulpina (L.) Hue');
insert into symptoms (id, symptomname) values (57, 'Penstemon montanus Greene var. idahoensis (Pennell & D.D. Keck) Cronquist');
insert into symptoms (id, symptomname) values (58, 'Diploschistes actinostomus (Ach.) Zalhbr.');
insert into symptoms (id, symptomname) values (59, 'Loeseliastrum depressum (M.E. Jones ex A. Gray) J.M. Porter');
insert into symptoms (id, symptomname) values (60, 'Carex macrocephala Willd. ex Spreng. var. bracteata T. Holm');
insert into symptoms (id, symptomname) values (61, 'Chamaesyce serpyllifolia (Pers.) Small ssp. serpyllifolia');
insert into symptoms (id, symptomname) values (62, 'Ebenopsis ebano (Berl.) Barneby & Grimes');
insert into symptoms (id, symptomname) values (63, 'Lobelia berlandieri A. DC. var. brachypoda (A. Gray) McVaugh');
insert into symptoms (id, symptomname) values (64, 'Sanicula peckiana J.F. Macbr.');
insert into symptoms (id, symptomname) values (65, 'Cladonia carneola (Fr.) Fr.');
insert into symptoms (id, symptomname) values (66, 'Platydesma H. Mann');
insert into symptoms (id, symptomname) values (67, 'Cyperus cyperoides (L.) Kuntze');
insert into symptoms (id, symptomname) values (68, 'Geum peckii Pursh');
insert into symptoms (id, symptomname) values (69, 'Eriogonum multiflorum Benth.');
insert into symptoms (id, symptomname) values (70, 'Quercus gambelii Nutt. var. gambelii');
insert into symptoms (id, symptomname) values (71, 'Physciella nepalensis (Poelt) Essl.');
insert into symptoms (id, symptomname) values (72, 'Dorycnium hirsutum (L.) Ser.');
insert into symptoms (id, symptomname) values (73, 'Silene scaposa B.L. Rob.');
insert into symptoms (id, symptomname) values (74, 'Carex nigra (L.) Reichard');
insert into symptoms (id, symptomname) values (75, 'Schizanthus Ruiz & Pav.');
insert into symptoms (id, symptomname) values (76, 'Lupinus ammophilus Greene');
insert into symptoms (id, symptomname) values (77, 'Lapsana communis L.');
insert into symptoms (id, symptomname) values (78, 'Leptogium milligranum Sierk');
insert into symptoms (id, symptomname) values (79, 'Fontinalis sphagnifolia (Müll. Hal.) Wijk & Margad.');
insert into symptoms (id, symptomname) values (80, 'Antennaria howellii Greene');
insert into symptoms (id, symptomname) values (81, 'Melanelia subelegantula (Essl.) Essl.');
insert into symptoms (id, symptomname) values (82, 'Trifolium olivaceum Greene');
insert into symptoms (id, symptomname) values (83, 'Arecastrum (Drude) Becc.');
insert into symptoms (id, symptomname) values (84, 'Hexalectris spicata (Walter) Barnhart var. spicata');
insert into symptoms (id, symptomname) values (85, 'Pertusaria oculata (Dicks.) Th. Fr.');
insert into symptoms (id, symptomname) values (86, 'Alsia Sull.');
insert into symptoms (id, symptomname) values (87, 'Umbilicaria krascheninnikovii (Savicz) Zahlbr.');
insert into symptoms (id, symptomname) values (88, 'Tournefortia hirsutissima L.');
insert into symptoms (id, symptomname) values (89, 'Antennaria flagellaris (A. Gray) A. Gray');
insert into symptoms (id, symptomname) values (90, 'Hymenophyllum brevifrons Kunze');
insert into symptoms (id, symptomname) values (91, 'Cerastium arvense L. ssp. maximum (Hollick & Britton) Ugborogho');
insert into symptoms (id, symptomname) values (92, 'Dictamnus L.');
insert into symptoms (id, symptomname) values (93, 'Bromus anomalus Rupr. ex Fourn.');
insert into symptoms (id, symptomname) values (94, 'Dalea carnea (Michx.) Poir.');
insert into symptoms (id, symptomname) values (95, 'Nicotiana acuminata (Graham) Hook. var. acuminata (Graham) Hook. [excluded]');
insert into symptoms (id, symptomname) values (96, 'Oxyspora paniculata (D. Don) DC.');
insert into symptoms (id, symptomname) values (97, 'Cyperus fendlerianus Boeckeler');
insert into symptoms (id, symptomname) values (98, 'Dubautia plantaginea Gaudich. ssp. magnifolia (Sherff) G.D. Carr');
insert into symptoms (id, symptomname) values (99, 'Linum carteri Small');
insert into symptoms (id, symptomname) values (100, 'Kleinhovia L.');